[package]
name = "cbsrs"
version = "0.1.0"
edition = "2021"
authors = ["Max Brown <max.carter-brown@aru.ac.uk>"]
description = "A Circular Binary Segmentation algorithm"
license = "MIT"

[dependencies]
rand = "0.8.5"
